library(MASS) # for the example dataset 
library(plyr) # for recoding data
library(ROCR) # for plotting roc
library(AUC) # for calculate AUC
library(class) # for knn
library(e1071) # for NB and SVM
library(rpart) # for decision tree
library(ada) # for adaboost

## set the seed so you can get exactly the same results whenever you run the code
set.seed(12345)

dataset <- load.data.pokemon()

## knn, k=3
cl.method <- 'knn'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## decision tree, default
cl.method <- 'dtree'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## SVM, default
cl.method <- 'svm'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## Logistic Regression
cl.method <- 'lr'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## Naive Bayesian
cl.method <- 'nb'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## Adaboost
cl.method <- 'ada'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## knn, k=5
## revise k=5 in function_do_classification.R first
cl.method <- 'knn'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## knn, k=7
## revise k=7 in function_do_classification.R first
cl.method <- 'knn'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## decision tree, pruned
## revise from 0 to 1 in function_do_classification.R first
cl.method <- 'dtree'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## SVM, linear kernel function
cl.method <- 'svmLin'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## SVM, polynomial kernel function
cl.method <- 'svmPoly'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## SVM, radius (Gaussian) kernel function
cl.method <- 'svmRad'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## SVM, Sigmoid kernel function
cl.method <- 'svmSig'
my.classifier(dataset, cl.name=cl.method, do.cv=T)

## multiple ROC curves generated by different model in one graph
cl <- c("knn","dtree","svmLin","lr","nb","ada")
color <- c("red","green","blue","cyan","magenta","yellow")

for(i in 1:6){
  result <- k.fold.cv.result(dataset, cl[i])
  pred=prediction(result$probs,result$actuals)
  perf=performance(pred, "tpr","fpr")
  if (i==1) {
    plot(perf, col=color[i])
  }
  else{
    plot(perf, add = TRUE, col=color[i])
    if (i==6){
      legend('bottomright', # places a legend at the appropriate place
             legend=cl, # puts text in the legend
             lty=1, # gives the legend appropriate symbols (lines)
             lwd=2,
             col=color, # gives the legend lines the correct color
             bty='n',
             cex=0.8,
             pt.cex=1,
             text.font=10,
             y.intersp=0.2)
      par(mar=c(5,4,4,2)+0.1)
    }
  }
}

## load normalized dataset
dataset <- load.data.norm.pokemon()
dataset[1:3,]

## knn, k=3
cl.method <- 'knn'
my.classifier(dataset, cl.name=cl.method, do.cv=T)